# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='immunization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name of the vaccine')),
                ('dose_no', models.IntegerField()),
                ('duration_in', models.CharField(choices=[('months', 'months'), ('years', 'years')], max_length=6, verbose_name='Select duration')),
                ('duration_from', models.IntegerField()),
                ('duration_to', models.IntegerField()),
            ],
        ),
    ]
