# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunization',
            name='total_dose',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
