# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_immunization_total_dose'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunization',
            name='description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
