# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_immunization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
