# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20161226_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunization',
            name='Type_of_dose',
            field=models.CharField(choices=[('recommended', 'recommended'), ('catching-up', 'catching-up')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
