# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_immunization_type_of_dose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunization',
            name='duration_in',
            field=models.CharField(choices=[('month', 'month'), ('year', 'year')], max_length=6, verbose_name='Select duration'),
        ),
    ]
