# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161227_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='date_of_admin',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='vaccine',
            field=models.ManyToManyField(through='main.Schedule', to='main.Immunization'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='immunization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Immunization'),
        ),
    ]
