# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161228_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='vaccine',
            field=models.ManyToManyField(through='main.Schedule', to='main.Immunization'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='immunization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Immunization'),
        ),
    ]
